### ISSUE TITLE
what does it mean to add & in front of the string？

### ISSUE THREAD

**Issue by vmtest888** [RPicster/godot4-demo-desert-light#3]
https://github.com/RPicster/godot4-demo-desert-light/blob/037ce70242d63e143ccd7e515f5ed071b146053d/src/scenes/Player/MovementController.gd#L29

```
	input_axis = Input.get_vector(&"move_back", &"move_forward",
			&"move_left", &"move_right")
```

Hello, may I ask, what does it mean to add & in front of the string?

**Comment by ClaudiuCeia** [comment]
See [StringName](https://docs.godotengine.org/en/stable/classes/class_stringname.html#class-stringname)
